name: "Run Code Scans"
# https://github.com/github/codeql-action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    #        â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ minute (0 - 59)
    #        â”‚  â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ hour (0 - 23)
    #        â”‚  â”‚ â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ day of the month (1 - 31)
    #        â”‚  â”‚ â”‚ â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ month (1 - 12 or JAN-DEC)
    #        â”‚  â”‚ â”‚ â”‚ â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ day of the week (0 - 6 or SUN-SAT)
    #        â”‚  â”‚ â”‚ â”‚ â”‚
    #        â”‚  â”‚ â”‚ â”‚ â”‚
    #        â”‚  â”‚ â”‚ â”‚ â”‚
    #        *  * * * *
    - cron: "30 1 * * 0"
  workflow_dispatch:

jobs:
  CodeQL-Scan:
    # CodeQL runs on ubuntu-latest, windows-latest, and macos-latest
    # runs-on: ubuntu-latest
    # runs-on: [self-hosted, ubuntu-20.04]
    runs-on: [self-hosted, coldstone, ghas-runner-linux]

    permissions:
      actions: read # only required for workflows in private repositories
      contents: read # for actions/checkout fetch code
      pull-requests: write # can write to pull requests
      security-events: write # required for all workflows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          # The amount of memory in MB that can be used by CodeQL extractors.
          # By default, CodeQL extractors will use most of the memory available in the system
          # (which for GitHub-hosted runners is 6GB for Linux, 5.5GB for Windows, and 13GB for macOS).
          # This input also sets the amount of memory that can later be used by the "analyze" action.
          ram: 1024
          # Using additional queries to get more results
          # See https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/customizing-code-scanning#using-queries-in-ql-packs
          queries: security-and-quality
        # with:
        #   debug: true
        # Override language selection by uncommenting this and choosing your languages
        # with:
        #   languages: go, javascript, csharp, python, cpp, java, ruby

      # Autobuild attempts to build any compiled languages (C/C++, C#, Go, or Java).
      # If this step fails, then you should remove it and run the build manually (see below).
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      # â„¹ï¸ Command-line programs to run using the OS shell.
      # ðŸ“š See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun

      # âœï¸ If the Autobuild fails above, remove it and uncomment the following
      #    three lines and modify them (or add more) to build your code if your
      #    project uses a compiled language

      # - run: |
      #   echo "Run, Build Application using script"
      #   ./location_of_script_within_repo/buildscript.sh

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: /codeql-scan:${{ github.job }}

  LanguageCheck:
    runs-on: [self-hosted, coldstone, ghas-runner-linux]

    outputs:
      contains_tf: ${{ steps.filechecks.outputs.contains_tf }}
      contains_pwsh: ${{ steps.filechecks.outputs.contains_pwsh }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: filechecks
        name: Check for Terraform and Powershell Files
        shell: bash
        # The set output is deprecated and will be disabled soon but the syntax they recommend gives ambiguous redirect error
        # - echo "KEY=VALUE" >> $GITUB_OUTPUT
        # https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
        # An example of a user getting this error due to an old runner being used
        # https://github.com/community/community/discussions/36746#discussioncomment-4059832
        run: |
          case `find $GITHUB_WORKPACE -name '*.tf' -print -quit` in
            '') echo 'No Terraform Files Found' ;;
            *) echo "::set-output name=contains_tf::true" ;;
          esac

          case `find $GITHUB_WORKPACE -name '*.ps1' -print -quit` in
            '') echo 'No PowerShell Files Found' ;;
            *) echo "::set-output name=contains_pwsh::true" ;;
          esac
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

  PowerShell-Scan:
    # CodeQL runs on ubuntu-latest, windows-latest, and macos-latest
    # runs-on: ubuntu-latest
    # runs-on: [self-hosted, ubuntu-20.04]
    runs-on: [self-hosted, coldstone, ghas-runner-linux]
    needs: LanguageCheck
    if: needs.LanguageCheck.outputs.contains_pwsh == 'true'

    permissions:
      actions: read # only required for workflows in private repositories
      contents: read # for actions/checkout fetch code
      pull-requests: write # can write to pull requests
      security-events: write # required for all workflows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Perform PowerShell Scan
        uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          # Check https://github.com/microsoft/psscriptanalyzer-action for more info about the options.
          # The below set up runs PSScriptAnalyzer to your entire repository and runs some basic security rules.
          path: .\
          recurse: true
          output: powershellresults.sarif

      - name: Upload PowerShell SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: powershellresults.sarif

  Terraform-Scan:
    # CodeQL runs on ubuntu-latest, windows-latest, and macos-latest
    # runs-on: ubuntu-latest
    # runs-on: [self-hosted, ubuntu-20.04]
    runs-on: [self-hosted, coldstone, ghas-runner-linux]
    needs: LanguageCheck
    if: needs.LanguageCheck.outputs.contains_tf == 'true'

    permissions:
      actions: read # only required for workflows in private repositories
      contents: read # for actions/checkout fetch code
      pull-requests: write # can write to pull requests
      security-events: write # required for all workflows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Perform Terraform Scan
        uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          sarif_file: tfsec.sarif

      - name: Upload Terraform SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec.sarif
