jobs:
  PowerShell-Scan:
    runs-on: im-ghas-linux

    permissions:
      actions: read # only required for workflows in private repositories
      contents: read # for actions/checkout fetch code
      pull-requests: write # can write to pull requests
      security-events: write # required for all workflows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Perform PowerShell Scan
        # Rules URL
        # https://github.com/PowerShell/PSScriptAnalyzer/blob/master/docs/Rules/README.md
        uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          # Check https://github.com/microsoft/psscriptanalyzer-action for more info about the options.
          # The below set up runs PSScriptAnalyzer to your entire repository and runs some basic security rules.
          path: .\
          recurse: true
          output: powershell.sarif

      - name: Upload PowerShell SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: powershell.sarif
