jobs:
  Terraform-Scan:
    runs-on: im-ghas-linux

    permissions:
      actions: read # only required for workflows in private repositories
      contents: read # for actions/checkout fetch code
      pull-requests: write # can write to pull requests
      security-events: write # required for all workflows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Perform Terraform Scan
        # Rules Lookup
        # https://aquasecurity.github.io/tfsec/v1.28.1/checks/azure/
        uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          sarif_file: terraform.sarif

      - name: Upload Terraform SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: terraform.sarif
