jobs:
  CodeQL-Scan-csharp:
    runs-on: PLACEHOLDER_RUNS_ON

    env:
      DOTNET_VERSION: |
        PLACEHOLDER_DOTNET_VERSION
      SOLUTION_FILE: PLACEHOLDER_SOLUTION_FILE
      DOTNET_INSTALL_DIR: PLACEHOLDER_DOTNET_INSTALL_DIR

    permissions:
      actions: read # only required for workflows in private repositories
      contents: read # for actions/checkout fetch code
      pull-requests: write # can write to pull requests
      security-events: write # required for all workflows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core without Install Directory
        if: env.DOTNET_INSTALL_DIR == 'NotUsed'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup .NET Core with Install Directory
        if: env.DOTNET_INSTALL_DIR != 'NotUsed'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        env:
          DOTNET_INSTALL_DIR: ${{ env.DOTNET_INSTALL_DIR }}

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          ram: 1536 # Give 1.5 GB ram to CodeQL, 1024 can lead to out of memory issues for some C# repos
          # Using additional queries to get more results
          # See https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/customizing-code-scanning#using-queries-in-ql-packs
          queries: security-and-quality
          languages: csharp

      - name: Authenticate with GitHub Packages
        uses: im-open/authenticate-with-gh-package-registries@v1.0.5
        with:
          read-pkg-token: ${{ secrets.READ_PKG_TOKEN }} # This is an org-level secret
          orgs: "PLACEHOLDER_ORG"

      - name: dotnet build
        run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release

      - name: Perform C# CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: /codeql-scan:csharp
