jobs:
  PowerShell-Scan:
    runs-on: im-ghas-linux

    permissions:
      actions: read # only required for workflows in private repositories
      contents: read # for actions/checkout fetch code
      pull-requests: write # can write to pull requests
      security-events: write # required for all workflows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Perform PowerShell Scan
        uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          # Check https://github.com/microsoft/psscriptanalyzer-action for more info about the options.
          # The below set up runs PSScriptAnalyzer to your entire repository and runs some basic security rules.
          path: .\
          recurse: true
          output: powershellresults.sarif

      - name: Upload PowerShell SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: powershellresults.sarif

      - name: PowerShell Rules Lookup Comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
              body: 'To view PowerShell rules go to [PSScriptAnalyzer Rules](https://github.com/PowerShell/PSScriptAnalyzer/blob/master/docs/Rules/README.md).'
            })
