jobs:
  CodeQL-Scan:
    strategy:
      matrix:
        languages: [PLACEHOLDER_MATRIX_LANGS]

    runs-on: im-ghas-linux

    permissions:
      actions: read # only required for workflows in private repositories
      contents: read # for actions/checkout fetch code
      pull-requests: write # can write to pull requests
      security-events: write # required for all workflows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # For JavaScript use filter-sarif action so we can remove results from dist folders
      # https://github.com/advanced-security/filter-sarif

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          ram: 1024
          # Using additional queries to get more results
          # See https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/customizing-code-scanning#using-queries-in-ql-packs
          queries: security-and-quality
          languages: ${{ matrix.languages }}

      # Autobuild attempts to build any compiled languages (C/C++, C#, Go, or Java).
      # If this step fails, then you should remove it and run the build manually (see below).
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      # ℹ️ Command-line programs to run using the OS shell.
      # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun

      # ✏️ If the Autobuild fails above, remove it and uncomment the following
      #    three lines and modify them (or add more) to build your code if your
      #    project uses a compiled language

      # - run: |
      #   echo "Run, Build Application using script"
      #   ./location_of_script_within_repo/buildscript.sh

      # Perform normal analysis
      - name: Perform CodeQL Analysis
        if: matrix.languages != 'javascript'
        uses: github/codeql-action/analyze@v2
        with:
          category: /codeql-scan:${{ matrix.languages }}

      # For JavaScript run analysis differently so we can ignore directories in the results
      - name: Perform JavaScript CodeQL Analysis
        if: matrix.languages == 'javascript'
        uses: github/codeql-action/analyze@v2
        with:
          category: /codeql-scan:${{ matrix.languages }}
          upload: False
          output: sarif-results

      - name: Filter JavaScript SARIF Results
        if: matrix.languages == 'javascript'
        # Information about this tool
        # https://github.com/advanced-security/filter-sarif
        uses: advanced-security/filter-sarif@09a9626fe5e89584ba5ed115143975bfc59ac6a9
        with:
          # Remove results under dist directory
          patterns: |
            -**/dist/**
          input: sarif-results/javascript.sarif
          output: sarif-results/javascript.sarif

      - name: Upload JavaScript SARIF Results
        if: matrix.languages == 'javascript'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sarif-results/javascript.sarif
